### ISSUE TITLE
由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败

### ISSUE THREAD

**Issue by droppiggy** [xsthunder/download-youtube-subtitle#5]
youtube账户要登录后才能下载吗？不然会报连接不上
![image](https://user-images.githubusercontent.com/29065995/101587831-f98b8680-3a1f-11eb-9bec-a0e77710e5c9.png)

**Comment by xsthunder** [comment]
请在运行本仓库的相同环境下尝试下面的命令，以确认是否能够访问youtube。
```
wget www.youtube.com
```

**Comment by xsthunder** [comment]
如果不通过，请设置环境http_proxy和http_proxys，参考[Using Anaconda behind a company proxy — Anaconda documentation](https://docs.anaconda.com/anaconda/user-guide/tasks/proxy/#environment-variables)
