### ISSUE TITLE
默认语言不是英语

### ISSUE THREAD

**Issue by Patrick-Rud** [xsthunder/download-youtube-subtitle#6]
>dl-youtube-cc vP4iY1TtS3s --translation en --to_json=True --output_file='tmp.json'
INFO:  available caption(s) will be displayed as original text:
INFO:  ✔ #0. .tr      土耳其文
INFO:  ⭕ #1. .zh-TW   中文（台灣）
INFO:  ⭕ #2. .zh-CN   中文（中國）
INFO:  ⭕ #3. .ja      日文
INFO:  ⭕ #4. .ne      尼泊爾文
INFO:  ⭕ #5. .id      印尼文
INFO:  ⭕ #6. .hi      印地文
INFO:  ⭕ #7. .es      西班牙文
INFO:  ⭕ #8. .es-419  西班牙文（拉丁美洲）
INFO:  ⭕ #9. .iw      希伯來文
INFO:  ⭕ #10. .ab      阿布哈茲文
INFO:  ⭕ #11. .ar      阿拉伯文
INFO:  ⭕ #12. .en      英文
INFO:  ⭕ #13. a.en     英文+(自動產生) automatically generated by youtube
INFO:  ⭕ #14. .th      泰文
INFO:  ⭕ #15. .cs      捷克文
INFO:  ⭕ #16. .sk      斯洛伐克文
INFO:  ⭕ #17. .pt-PT   葡萄牙文（葡萄牙）
INFO:  ⭕ #18. .de      德文
INFO:  ⭕ #19. .ko      韓文
INFO:  ✔ marks chosen one,  given by --caption_num in 0-index, default to 0
INFO:  Save to  tmp.json

**Comment by xsthunder** [comment]
Thank you for using this lib.
In this case, translation option is not available due to the limit of youtube. Simply use `caption_num` to retrive the caption.
```bash
dl-youtube-cc vP4iY1TtS3s --caption_num=12 --to_json=True --translation False --output_file='tmp.json'
```
where `--caption_num=12` denotes the chosen caption.

**Comment by xsthunder** [comment]
New in v1.1.0, you may [use `--caption_num` and `--caption_num_second`](https://github.com/xsthunder/download-youtube-subtitle/tree/v1.1.0#use-caption_num-caption_num_second-to-get-full-control) to choose the caption which will be displayed as original or translation transcript.

```
pip uninstall download-youtube-subtitle -y
pip install download-youtube-subtitle=1.1.0
```
